### ISSUE TITLE
Default rulesFile

### ISSUE THREAD

**Issue by ValentinGot** [groupe-sii/sonar-web-frontend-reporters#1]
Default **rulesFile** property aren't working.

**Comment by graflann** [comment]
I encountered this as well. The rulesFile value needs to be an object with a configuration key/value, per the gulp-tslint docs: [https://github.com/panuhorsmalahti/gulp-tslint](). Looking at the src, the rulesFile value is passed directly into the gulp-tslint instance and doesn't resolve properly without the nested configuration.

This configuration key needs to resolve to a value of either a string literal path or an object containing the rules key/value, rulesDirectory key/value, etc.

Hope it helps.

**Comment by ValentinGot** [comment]
Now working on **3.0.0-beta**
