### ISSUE TITLE
Severity rating on Sonar

### ISSUE THREAD

**Issue by lucascampelo** [groupe-sii/sonar-web-frontend-reporters#16]
Using `sonar-web-frontend-reporters` v3.0.0 with node v4.5.0, the eslint reports always are rating as **info**. How to change to **major** ?

**Comment by ValentinGot** [comment]
You can't, seems like there is a problem.
`eslint` is giving us it's severity depending on the rule.

**Comment by lucascampelo** [comment]
Debugging `message` on [this line](https://github.com/groupe-sii/sonar-web-frontend-reporters/blob/master/lib/reporters/eslint.reporter.js#L51), seems `message.type` do not exists. Maybe using `message.severity` wouldn't be more useful ?

**Comment by ValentinGot** [comment]
Yep thanks, i spot it too :)

It's fixed and waiting to be released 4b2ef41 dbba717

**Comment by ValentinGot** [comment]
Released in **3.1.0**.

**Comment by lucascampelo** [comment]
Seems on version **3.1.0**, the build files (eslint, eslint-angular, css and htmlhint) still using `message.type`. I'm using **3.1.0** and Sonar still reporting errors as `info` or `low priority`

**Comment by ValentinGot** [comment]
Arf yeah, it looks like a fail ... Will fix it as soon as possible :)
