### ISSUE TITLE
Problem installing sonar-web-frontend-reporters off-line

### ISSUE THREAD

**Issue by gfrancesca** [groupe-sii/sonar-web-frontend-reporters#19]
Hi, 
I have 
node v6.9.5
npm  v3.10.10

I need to install sonar web frontend reporters on an offline machine.
I alredy tried with npmbox and npmunbox, but I always have errors.
Now I'm trying with offline-npm.
when I try to pack the module with npm pack I have the folliwing error:

npm ERR! addLocal Could not install C:\Users\fguarino\AppData\Roaming\npm\node_m
odules\sonar-web-frontend-reporters
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "pack"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sonar-web-frontend-reporters@3.2.0 prepublish: `./offline/offline-npm -
-prepublish ; npm run-script build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonar-web-frontend-reporters@3.2.0 prepublish script './o
ffline/offline-npm --prepublish ; npm run-script build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonar-web-frontend-re
porters package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./offline/offline-npm --prepublish ; npm run-script build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonar-web-frontend-reporters
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonar-web-frontend-reporters
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fguarino\AppData\Roaming\npm\node_modules\sonar-web-fronte
nd-reporters\npm-debug.log

[npm-debug.txt](https://github.com/groupe-sii/sonar-web-frontend-reporters/files/760135/npm-debug.txt)

could you please help me in some way? 
Thanks
Francesca

**Comment by ValentinGot** [comment]
Hi,

It seems to works fine for me with **offline-npm**, are you sure it doesn't come from elsewhere ?

```sh
~/Workspace/test
offline-npm --add
    offline-npm was added to project: test

~/Workspace/test
npm install sonar-web-frontend-reporters --save

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global jshint@2.9.4 should be installed with -g
test@1.0.0 /home/valentin/Workspace/test
└─┬ sonar-web-frontend-reporters@3.2.0 
...

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

~/Workspace/test                                                                                                                                                                                                                              
npm pack

> test@1.0.0 prepublish /home/valentin/Workspace/test
> ./offline/offline-npm --prepublish ; 

test@1.0.0 /home/valentin/Workspace/test
└─┬ sonar-web-frontend-reporters@3.2.0 
...

wrote npm-shrinkwrap.json
test-1.0.0.tgz
```

**Comment by gfrancesca** [comment]
Hi, 
thanks for your answer and for your suggest, I think you' re right: 
I found this: #https://github.com/commenthol/offline-npm/issues/4.
Windows shit.

However, I resolved my problem copying the web-frontend-reporter package and relative cmd file in the right place on the offline machine and it works. 

thanks for help

Francesca

**Comment by ValentinGot** [comment]
Glad i could help :)
