### ISSUE TITLE
.eslintignore not read when generating eslint report

### ISSUE THREAD

**Issue by raghav154** [groupe-sii/sonar-web-frontend-reporters#20]
I have .eslintrc and also .eslintignore file.
The .eslintignore file is not being read by the sonar reporter. How do I specify ignorepaths/files in the .srreporterrc ?
I need to specify multiple files/folders hence a way to point to .eslintignore while running ESLint would help

**Comment by ValentinGot** [comment]
Hi,

You can now add the .eslintignore path by specifying the `ignorePath` option.

e.g:
```json
{
  "eslint": {
    "src": "src/**/*.js",
    "report": "reports/sonar/eslint.json",
    "rulesFile": ".eslintrc",
    "ignorePath": ".eslintignore"
  }
}
```
