### ISSUE TITLE
HTMLHint JSON output can be invalid

### ISSUE THREAD

**Issue by jh409** [groupe-sii/sonar-web-frontend-reporters#7]
Hi,

I currently have an issue where the HTML reporter is producing invalid JSON when the offending HTML is on a new line. 

For example, this HTML:

> &lt;button class="cancelButton"
> onclick="return false;"&gt;Cancel&lt;/button>

produces this invalid JSON in the report:

>   {
>              "line": 62,
>           "message": "Inline script [ 
>           onclick = 'return false;'] cannot be use.",
>       "description": "Inline script cannot be use.",
>       "rulekey": "inline-script-disabled",
>       "severity": "MINOR",
>       "reporter": "htmlhint",
>       "creationDate": 1472831618394
>   }

I'm also using your frontend plugin, which then throws an exception when it tries to parse this JSON. 

I realise that this is due to the handling of the message in HTMLHint [rule itself](https://github.com/yaniswang/HTMLHint/blob/master/src/rules/inline-script-disabled.js), but I don't think that's trying to create JSON, whereas the HTML reporter here is, hence why I'm reporting it here.

If you think it's an issue with the original HTMLHint, I will report it there instead.

**Comment by cedric-legallo** [comment]
Hi, this issues was fixed a fex time ago by this commit : 
https://github.com/groupe-sii/sonar-web-frontend-reporters/commit/2d57cead4be6d59cd0bdc2964215b44fb3cff6c1

but this version is not on npm at the moment.
I'll fix that today

**Comment by jh409** [comment]
Great, thanks!
